//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartfiveDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCharge
    {
        public int D_Id { get; set; }
        public Nullable<int> D_Price { get; set; }
        public Nullable<int> D_Percentage { get; set; }
    }
}
