//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartfiveDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_Id { get; set; }
        public Nullable<int> Order_Quantity { get; set; }
        public int Item_Id { get; set; }
        public int OL_Id { get; set; }
    
        public virtual OrderList OrderList { get; set; }
    }
}
