//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartfiveDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int R_Id { get; set; }
        public Nullable<int> R_Stars { get; set; }
        public string R_Description { get; set; }
        public int Item_Id { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
