<?xml version="1.0" encoding="utf-8"?><Database Name="PagalMart" Class="LINQMartFiveDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\PagalMart.mdf;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PagalMartConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Item_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Item_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Item_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Item_Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Item_Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pic_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCat_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Picture_Item" Member="Picture" ThisKey="Pic_Id" OtherKey="Pic_Id" Type="Picture" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Picture" Member="Pictures">
    <Type Name="Picture">
      <Column Name="Pic_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pic_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Picture_Item" Member="Items" ThisKey="Pic_Id" OtherKey="Pic_Id" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="User_Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="User_Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="User_Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="User_Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>